projects:
  prisma:
    schemaPath: ../src/server/prisma/generated/prisma.graphql
    extensions:
      prisma: prisma.yml
      
      codegen:
      - generator: prisma-binding
        language: typescript
        output:
          binding: ../src/server/prisma/generated/prisma.ts
    